# vim: set sw=2 ts=2 softtabstop=2 expandtab:
language: csharp
sudo: true
solution: "Source/Boogie.sln"
env:
  - BOOGIE_CONFIG=Debug
  - BOOGIE_CONFIG=Release
install:
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com C504E590
  # FIXME: We should not be using GPUVerify's repo for Z3
  - sudo sh -c 'echo "deb http://ppa.launchpad.net/delcypher/gpuverify-smt/ubuntu precise main" > /etc/apt/sources.list.d/smt.list'
  - sudo apt-get update
  - nuget restore ${TRAVIS_SOLUTION}
  # Install Z3
  - sudo apt-get -y install z3=4.3.2-0~precise2
  # Install needed python tools
  - sudo pip install lit OutputCheck pyyaml
  - mkdir -p Source/packages && cd Source/packages && nuget install NUnit.Runners -Version 2.6.3
  - cd ../../
script:
  - xbuild /p:Configuration=${BOOGIE_CONFIG} ${TRAVIS_SOLUTION}
  # Run unit tests
  - python Source/UnitTests/run-unittests.py ${BOOGIE_CONFIG}
  # Run driver tests
  - ln -s /usr/bin/z3 Binaries/z3.exe
  - lit -v Test/
